name: test_env_xgcm
channels:
  - numba
dependencies:
  - python
  - numpy
  - llvmlite
  - pytest
  - pip
  - pip:
    - docrep<=0.2.7
    - codecov
    - pytest-cov
    - pytest-xdist
    - git+https://github.com/pydata/xarray.git
    - git+https://github.com/dask/dask.git
    - git+https://github.com/dask/distributed.git
    - toolz
    - git+https://github.com/numba/numba.git
